import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { ZustandHydrationProvider } from "@/providers/zustand-hydration-provider";
import { cookies } from "next/headers";
import { generateColorCSS } from "@/lib/color-css-generator";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read color customization from cookies
  const cookieStore = await cookies();
  const colorHuesCookie = cookieStore.get("color-hues");

  let customColorCSS: string | null = null;
  if (colorHuesCookie?.value) {
    try {
      const hues = JSON.parse(colorHuesCookie.value);
      customColorCSS = generateColorCSS(hues);
    } catch (error) {
      console.error("Failed to parse color hues from cookie:", error);
    }
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Inject custom colors before page renders to prevent flash */}
        {customColorCSS && (
          <style
            id="custom-colors-server"
            dangerouslySetInnerHTML={{ __html: customColorCSS }}
          />
        )}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ZustandHydrationProvider>{children}</ZustandHydrationProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
